direction: right

pr: {
  label: PR opened
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
  shape: image
  height: 75
}
rpr: {
  label: Release PR merged
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
  shape: image
  height: 75
}

preview: preview environment {
  style.font-size: 20
  pr-dep: preview deployment {
    style.multiple: true
  }
  release-dep: staging deployment
}
prod: production environment {
  style.font-size: 20
  prod-dep: production deployment
}

pr -> preview.pr-dep: deploys
rpr -> preview.release-dep: deploys
preview.release-dep -> prod.prod-dep: promoted
