direction: right

local-environment: local environment {
  style.font-size: 20
  local-env: local deployment
  firebase-emulators: {
    label: local emulators
    icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/firebase_logo_icon_171157.png
    shape: image
    height: 50
  }
  local-env -> firebase-emulators
}

preview: preview environment {
  direction: right
  style.font-size: 20
  pr-dep: preview deployment {
    style.multiple: true
  }
  firebase-dev: {
    label: dev project
    icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/firebase_logo_icon_171157.png
    shape: image
    height: 50
  }
  pr-dep -> firebase-dev
  staging-dep: staging deployment
  staging-dep -> firebase-dev
}
prod: production environment {
  style.font-size: 20
  prod-dep: production deployment
  firebase-prod: {
    label: prod project
    icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/firebase_logo_icon_171157.png
    shape: image
    height: 50
  }
  prod-dep -> firebase-prod
}
