#!/usr/bin/env bash
set -euo pipefail

# pg_dump script exported from supabase db dump command
# we're not using the supabase db dump command because it requires the Docker daemon to create a container
# making this impossible to run in a container

export PGHOST="localhost" # run inside the db container
export PGUSER="postgres"
export PGPASSWORD="your-super-secret-and-long-postgres-password"
export PGDATABASE="postgres"

# Disable triggers so that data dump can be restored exactly as it is
echo "SET session_replication_role = replica;
"

pg_dump \
    --dbname=postgresql://$PGUSER:$PGPASSWORD@$PGHOST/$PGDATABASE \
    --data-only \
    --quote-all-identifier \
    --exclude-schema "" \
    --exclude-table "auth.schema_migrations" \
    --exclude-table "storage.migrations" \
    --exclude-table "supabase_functions.migrations" \
    --schema "auth|public" \
    --column-inserts --rows-per-insert 100000 --exclude-table \"auth\".\"audit_log_entries\"

# Reset session config generated by pg_dump
echo "RESET ALL;
"
