direction: right

user: {
  label: Visitor
  icon: assets/img/user-icon.svg
  shape: image
  height: 50
}

vercel: {
  web: web server {
    icon: assets/img/svelte-logo.svg
  }
}

supabase: {
  back: backend {
    icon: assets/img/supabase-logo.svg
  }
}

user -> vercel
vercel.web -> supabase.back: HTTPS
