direction: right

user: {
  label: Visitor
  icon: https://icons.terrastruct.com/essentials%2F359-users.svg
  shape: image
  height: 50
}

vercel: {
  web: web server {
    icon: https://raw.githubusercontent.com/sveltejs/branding/master/svelte-logo-square.svg
  }
}

supabase: {
  back: backend {
    icon: https://seeklogo.com/images/S/supabase-logo-DCC676FFE2-seeklogo.com.png
  }
}

user -> vercel
vercel.web -> supabase.back: HTTPS
