direction: right

supabase: Supabase \n Project {
  icon: assets/img/supabase-logo.svg
  shape: image
  height: 75
}

vercel-preview: {
  label: Vercel Preview Env \n pr-xxx.vercel.app
  icon: assets/img/vercel-logo.svg
  shape: image
  height: 75
}

vercel-production: {
  label: Vercel Production Env \n blazing-fire.app
  icon: assets/img/vercel-logo.svg
  shape: image
  height: 75
}

pr: {
  label: push to any branch \n but main
  icon: assets/img/github-logo.svg
  shape: image
  height: 75
}

push-main: {
  label: push to main
  icon: assets/img/github-logo.svg
  shape: image
  height: 75
}

pr -> vercel-preview -> supabase
push-main -> vercel-production -> supabase
