name: CI

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review

env:
  CI: true
  GCLOUD_BUCKET_NAME: blazing-fire-playwright-reports

jobs:
  continous-integration:
    if: github.event.pull_request.draft == false
    name: CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.3

      - name: Install project dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run format:check

      - name: Run ESLint check
        run: npm run lint

      - name: Run Vitest Unit Tests
        run: npm run test:unit

      - name: Setup .env
        run: |
          cp .env.example .env

      - name: Pull docker images
        run: docker compose --profile test pull

      - name: Up the apps
        run: docker compose up --detach --wait --build

      - name: Setup the DB
        run: |
          npm run db:reset

      - name: Run test
        id: e2e-tests
        continue-on-error: true
        run: docker compose run --rm --env CI=true test

      - name: Authenticate to Google Cloud
        if: steps.e2e-tests.outcome == 'failure'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - name: Set 'TEST_REPORT_URL'
        if: steps.e2e-tests.outcome == 'failure'
        run: echo "TEST_REPORT_URL=https://storage.googleapis.com/${{ env.GCLOUD_BUCKET_NAME }}/pr-${{ github.event.number }}/playwright-report/index.html" >> $GITHUB_ENV

      - name: Upload Playwright report
        if: steps.e2e-tests.outcome == 'failure'
        id: upload-report
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'apps/web'
          glob: 'playwright-**/**'
          destination: '${{ env.GCLOUD_BUCKET_NAME }}/pr-${{ github.event.number }}'
          process_gcloudignore: false
          parent: false
          gzip: false

      - name: Update PR Test Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{ github.event.number }}
          mode: ${{ steps.e2e-tests.outcome == 'failure' && 'upsert' || 'delete' }}
          comment_tag: test-report
          message: |
            :dizzy_face: **Playwright tests suite has failed!**
            :performing_arts: Report is available [here](${{ env.TEST_REPORT_URL }}).

      - name: Fail if E2E tests failed
        if: steps.e2e-tests.outcome == 'failure'
        run: exit 1
