name: Deploy Deployment Environment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ALIAS: blazing-fire-dev
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_DEV_PROJECT_ID }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_DEV_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}
  SUPABASE_DIRECTORY: apps/web
on:
  push:
    branches: 'main'

jobs:
  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.3

      - name: Install Vercel CLI
        run: npm install --global vercel@34.2.6

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.150.0

      - name: Link Supabase project
        working-directory: ${{ env.SUPABASE_DIRECTORY }}
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Push migration (if any)
        working-directory: ${{ env.SUPABASE_DIRECTORY }}
        run: supabase db push

      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: echo "deployment-url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Set Alias to Deployment
        run: vercel alias set ${{ steps.deployment.outputs.deployment-url }} ${{ env.VERCEL_ALIAS }} --token=${{ secrets.VERCEL_TOKEN }}
