name: Deploy Preview Environment

env:
  VERCEL_DEPLOY: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.3

      - name: Install Vercel CLI
        run: npm install --global vercel@32.5.0

      - name: Set 'VERCEL_ALIAS'
        run: echo "VERCEL_ALIAS=blazing-fire-preview-pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Get git information for the current branch
        id: git-info
        uses: ./.github/actions/git-info

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          PUBLIC_VERSION: preview

      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: echo "deployment-url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Set Alias to Deployment
        run: vercel alias set ${{ steps.deployment.outputs.deployment-url }} ${{ env.VERCEL_ALIAS }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set 'ENVIRONMENT_URL'
        run: echo "ENVIRONMENT_URL=https://${{ env.VERCEL_ALIAS }}.vercel.app" >> $GITHUB_ENV

      - name: Populate environment information in message template
        run: |
          sed -i 's|\$VERCEL_ALIAS|${{ env.VERCEL_ALIAS }}|g' .github/templates/deploy/ephemeral.md
          sed -i 's|\$ENVIRONMENT_URL|${{ env.ENVIRONMENT_URL }}|g' .github/templates/deploy/ephemeral.md
          sed -i 's|\$MOST_RECENT_COMMIT_SHA|${{ steps.git-info.outputs.most-recent-commit-sha }}|g' .github/templates/deploy/ephemeral.md
          sed -i 's|\$MOST_RECENT_COMMIT_NAME|${{ steps.git-info.outputs.most-recent-commit-name }}|g' .github/templates/deploy/ephemeral.md

      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.2
        with:
          content: .github/templates/deploy/ephemeral.md
          contentIsFilePath: true
          regex: '<!-- preview_start_match -->.*?<!-- preview_end_match -->'
          regexFlags: ims
          token: ${{ secrets.GITHUB_TOKEN }}
