name: Deploy Vercel Preview Environment

env:
  VERCEL_DEPLOY: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.3

      - name: Install Vercel CLI
        run: npm install --global vercel@32.5.0

      - name: Set 'VERCEL_ALIAS'
        run: echo "VERCEL_ALIAS=blazing-fire-preview-pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set 'MOST_RECENT_COMMIT_SHA'
        run: echo "MOST_RECENT_COMMIT_SHA=$(git log --format=%h -n 1)" >> $GITHUB_ENV

      - name: Set 'MOST_RECENT_COMMIT_NAME'
        run: echo "MOST_RECENT_COMMIT_NAME=$(git log --pretty=format:"%s" -n 1)" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: echo "deployment-url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Set Alias to Deployment
        run: vercel alias set ${{ steps.deployment.outputs.deployment-url }} ${{ env.VERCEL_ALIAS }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set 'ENVIRONMENT_URL'
        run: echo "ENVIRONMENT_URL=https://${{ env.VERCEL_ALIAS }}.vercel.app" >> $GITHUB_ENV

      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.2
        if: steps.e2e-tests.outcome == 'failure'
        with:
          content: "<!-- e2e_start_match -->\n**Preview environment live at [${{ env.VERCEL_ALIAS }}.vercel.app](${{ env.ENVIRONMENT_URL }})**\n:octocat: Commit deployed: `${{ env.MOST_RECENT_COMMIT_SHA }}` - `${{ env.MOST_RECENT_COMMIT_NAME }}`\n<!-- e2e_end_match -->"
          regex: '<!-- e2e_start_match -->.*?<!-- e2e_end_match -->'
          regexFlags: ims
          token: ${{ secrets.GITHUB_TOKEN }}
