name: Release Please

env:
  TOKEN: ${{ secrets.TOKEN_RELEASE_PLEASE }}

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          token: ${{ env.TOKEN }}
