name: Vercel Staging Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  PUBLIC_ENVIRONMENT: staging

on:
  push:
    tags:
      - '*'

jobs:
  deploy-preview:
    name: Deploy Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set 'VERCEL_ALIAS'
        run: |
          tag_with_dashes=$(echo "${{ github.ref_name }}" | sed 's/\./-/g')
          echo "VERCEL_ALIAS=blazing-fire-staging-$tag_with_dashes" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Vercel CLI
        run: npm install --global vercel@32.5.0

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: echo "deployment-url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Set Alias to Deployment
        run: vercel alias set ${{ steps.deployment.outputs.deployment-url }} ${{ env.VERCEL_ALIAS }} --token=${{ secrets.VERCEL_TOKEN }}
